package lib

var fileTemplate = `
var %s = &file{
	fileInfo: &fileInfo{
		name:  "%s",
		isDir: %t,
		size:  %d,
		mode:  os.FileMode(%d),
		mTime: time.Unix(%d, 0),
		cType: "%s",
	},
	path:  "%s",
	dirP:  "%s",
	sPath: "%s",
	id:    %d,
	cb:    %s,
}
`

var fileBytesTemplate = `
var %s = []byte("%s")
`

var headerTemplate = `/*
CODE GENERATED BY "github.com/wrfly/bindata" 
@%s

Files:%s

DO NOT EDIT!
*/

package %s

import (
	"os"
	"time"
)
`

var footerTemplate = `
func init() {
    fs = []*file{%s
	}

	root = &data{
		prefix: "%s",
		files:  make(map[string]*file, len(fs)),
	}
}
`
